name: angya
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # riverpod
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  json_annotation:

  # statenotifier
  state_notifier: ^0.7.2+1

  path_provider:

  # image
  image_picker:
  image_cropper:
  flutter_image_compress:

  pull_to_refresh:

  extended_nested_scroll_view: ^5.1.0

  permission_handler:

  # Firebase
  firebase_core: ^1.17.1
  firebase_analytics:
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  cloud_functions:
  firebase_messaging:
  firebase_crashlytics:

  # Widget
  dismissible_page:

  # Other
  package_info:
  uuid: ^3.0.6
  hashids2: ^2.0.0
  collection: ^1.16.0

  # Extended Stream
  rxdart:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  pedantic_mono: ^1.19.2

  json_serializable:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  flutter_gen_runner:

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


